### ISSUE TITLE
Contents of full height heros aren't positioned correctly in Internet Explorer 11

### ISSUE THREAD

**Issue by 1lann** [jgthms/bulma#186]
### Checklist

* [x] This is about Bulma the **CSS framework** and **not** about the Bulma website
* [x] I'm using Bulma **version** 0.0.23
* [x] My **browser** is: Internet Explorer 11 on Windows 8.1
* [ ] This is a **Sass** issue.
* [x] I am sure this issue is **not a duplicate**?

### Description

The positions of content and footer elements in full height heros are incorrect in Internet Explorer 11. This can be reproduced on the bulma.io website, and I've also reproduced it on my own website when I used Bulma version 0.0.23.

Screenshots from the bulma.io website:
<img width="1349" alt="screen shot 2016-04-24 at 9 56 09 pm" src="https://cloud.githubusercontent.com/assets/804919/14768074/d18c17ac-0a69-11e6-81d8-59bbc1b4b61e.png">
<img width="1348" alt="screen shot 2016-04-24 at 10 12 40 pm" src="https://cloud.githubusercontent.com/assets/804919/14768075/d269d13c-0a69-11e6-8c75-1babca6907a3.png">

### Steps to Reproduce

1. Visit bulma.io on Internet Explorer 11.
2. Scroll down to the full height hero example.

_Expected behavior:_ The content element would be vertically and horizontally centered, and the footer element would actually be at the bottom of the hero.

_Actual behavior:_ Position of the content element is to the left and is not vertically centered, and the footer element is directly below the content element rather than being at the bottom of the full height hero.

**Comment by jgthms** [comment]
Argh, thanks for pointing that out.

Unfortunately, there isn't much I can do about it.

**Comment by 1lann** [comment]
It works fine if you use 
```css
height: 100vh;
```
on the `.is-fullheight`, and then
```css
align-items: center;
```
on the `.hero-content`.
<img width="1349" alt="screen shot 2016-04-25 at 11 42 18 am" src="https://cloud.githubusercontent.com/assets/804919/14773296/0317d100-0adb-11e6-9c59-73e28565c38a.png">
<img width="1349" alt="screen shot 2016-04-25 at 11 41 32 am" src="https://cloud.githubusercontent.com/assets/804919/14773301/09c9510e-0adb-11e6-91c2-c7d60ef2d0cf.png">
Would you consider adding that?

**Comment by tquetano-r7** [comment]
For `.hero.is-fullheight`, the `min-height` is already set to `100vh`, and I'm not sure why you would want a hero to be larger than the screen size. Is changing `min-height` to `height` insufficient? Do you need to set `align-items` to `center` as well?

**Comment by 1lann** [comment]
@tquetano-r7 Sorry for the late reply.
> For `.hero.is-fullheight`, the `min-height` is already set to `100vh`, and I'm not sure why you would want a hero to be larger than the screen size.
I guess it's for cases where you have really small screens i.e. mobile phones.
> Is changing `min-height` to `height` insufficient? Do you need to set `align-items` to `center` as well?
Yes you need to set align-items to center if you want objects to be spaced correctly and to be centered. The second example with the tabs and navigation bar won't render correctly without `align-items` set to `center`. The first example that says "Easy vertical centering in fullscreen" will render correctly, however.

**Comment by jgthms** [comment]
I'm serving the CSS with autoprefixer. This should work now.

**Comment by jeffijoe** [comment]
@jgthms this has not been fixed just yet.

![image](https://cloud.githubusercontent.com/assets/2505474/19770910/52a4c62a-9c61-11e6-9f09-7d57d6e0f696.png)

**Comment by Schnouki** [comment]
`min-height` being insufficient is actually a known issue in IE11: https://github.com/philipwalton/flexbugs#3-min-height-on-a-flex-container-wont-apply-to-its-flex-items

**Comment by gbourgneuf** [comment]
This issue is not fixed on bulma 0.2.3 :-(

Can you please add height: 100vh to hero.is-fullheight .body and align-items center to be able to use it on IE11 please ?

Regards

**Comment by Wikiki** [comment]
Hi,

I also found that the following rule
```
& > .container
        flex-grow: 1
        flex-shrink: 1
```
Breaks the horizontal positioning on IE11.

**Comment by chrisribe** [comment]
Is still and issue when trying to use hero full height under internet explorer...
