### ISSUE TITLE
button.button trouble in firefox

### ISSUE THREAD

**Issue by necinc** [jgthms/bulma#219]
I found a small bug in case when we use `.button` class name with tag  `<button>`
You usually showed `.button` with `<a>` and everything was normal, but if I want to use

``` html
<button class="button">
    <span class="icon">
        <i class="fa fa-bug">
    </span>
    <span>
         Some button
    </span>
</button>
```

my markup becomes broken

I do a small pen which shows it
http://codepen.io/necinc/pen/ZOzmmb
(Note: You need to watch it in firefox. I use FF v.43.0)

There must to be something like this:
![button troubles](http://i.imgur.com/yW13TlK.png)

**Comment by jgthms** [comment]
Yeah it used to be `inline-block` before but `inline-flex` is easier to use.

**Comment by cristicbz** [comment]
Why 'wontfix'? What is the solution? Provide the CSS workaround to override to `inline-block`? I'd rather not use `a` when the semantics indicate a `button` is more appropriate.

**Comment by uptownhr** [comment]
I'd like to also add that a simple button with the class button is also bugged.  For example, below will contain a button but the text will not be vertically aligned but aligned to the bottom.

Also the same for input where type=button

```
<button class="button">mis-aligned</button>
<input type="button" value="mis-aligned" />
```

**Comment by slikts** [comment]
Here's [the Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=984869) in question (fixed in Firefox nightly). In short, Firefox ignores the `display` property for `button` elements. The fix is to wrap the button contents with a flex element.

Bulma should probably either make a note about this issue in the docs or have additional containers in all the buttons by default.

**Comment by jeffijoe** [comment]
Man-O-Man-O-Man do I wish I found this issue 3 hours ago. _It can't possibly be that in the docs they use `<a>` and I use `<button>`, no way!_ 💩

**Comment by alqu** [comment]
Hm, same with me. Replacing all `<button>` with `<a>` works in FF.

**Comment by kenmaclord** [comment]
Still buggy with 51.0.1 and bulma 0.3.1. Obviously in many cases it's not possible to change button tag to a tag. Especially in forms.

Is there a solution to have an icon button with a regular button tag ?

**Comment by slikts** [comment]
Just wrap the button contents with a flex element and it will work fine.
